/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/hot_air_balloon.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Hot_air_balloon(props) {
  const { nodes, materials } = useGLTF('./models/hot_air_balloon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Hot_Air_Balloon.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/hot_air_balloon.glb')
