/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/remains/remains.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Remains(props) {
  const { nodes, materials } = useGLTF('./models/remains/remains.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.dolmen1001.geometry} material={materials.Material}>
        <mesh geometry={nodes.dolmen1.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1002.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1003_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1004.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1005.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1006.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1007.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1008.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1009.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1010.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1011.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1012.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1013.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1014.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1015.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1016.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1017.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1018.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1019.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen1020.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen2.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen2001.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen2002.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen2003.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen2004.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen2005.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen3.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen3001.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen3002.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen4.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen4001.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen4002.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen4003.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen4004.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen4005.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen4006.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen4007.geometry} material={materials.Material} />
        <mesh geometry={nodes.dolmen4008.geometry} material={materials.Material} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/remains.gltf')
